#!/usr/bin/env python3
import pyautogui
import math

h = pyautogui.position().x
k = pyautogui.position().y
angle = 0
r = 100

def get_next_point_on_circle():
    global r, h, k, angle
    if angle >= 360:
        angle = 0
    l_x = r * math.cos(math.radians(angle))
    l_y = r * math.sin(math.radians(angle))
    y = k + l_y
    x = h + l_x
    angle += 1 
    return (x, y)


def check_center_changed(x, y):
    global r, h, k, angle
    l_x = r * math.cos(math.radians(angle))
    l_y = r * math.sin(math.radians(angle))
    h_hat = x - l_x
    k_hat = y - l_y
    if int(h_hat) != int(h):
        h = h_hat
    if int(k_hat) != int(k):
        k = k_hat


while (True):
    try:
        x, y = get_next_point_on_circle()
        check_center_changed(x, y)
        pyautogui.moveTo(x, y, _pause=False)
    except KeyboardInterrupt:
        exit()